name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push codebase to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Use your exact Hugging Face Space URL from your third screenshot
          git push --force https://martinsuasnavar:$HF_TOKEN@huggingface.co/spaces/martinsuasnavar/prototype-gpt-server main